export const TouristSites = [
    {
      id: '1',
      name: "Eiffel Tower",
      location: "Paris, France",
      rating: '4.8',
      price: '25',
      image:
        "https://picsum.photos/id/2/800/600",
      photos:[
        "https://picsum.photos/id/2/800/600",
        "https://picsum.photos/id/2/800/600",
        "https://picsum.photos/id/2/800/600",
        "https://picsum.photos/id/2/800/600",
      ],
      tripPlan:
        "Spend a day in Paris exploring the Eiffel Tower and the surrounding Champ de Mars. Consider visiting the nearby Louvre Museum and taking a cruise along the Seine River to see more of the city's iconic sights.",
      to:'6/7/2064',
      from:'8/5/2118',
    },
    {
      id: '2',
      name: "Machu Picchu",
      location: "Cusco, Peru",
      rating: '4.9',
      price: '60',
      image:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/1024px-Machu_Picchu%2C_Peru.jpg",
      photos:[
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/1024px-Machu_Picchu%2C_Peru.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/1024px-Machu_Picchu%2C_Peru.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/1024px-Machu_Picchu%2C_Peru.jpg",
        "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/1024px-Machu_Picchu%2C_Peru.jpg",
      ],
      tripPlan:
        "Spend 2-3 days exploring Machu Picchu and the surrounding Inca Trail. Consider hiking the Inca Trail or taking the train to Aguas Calientes, the town at the base of Machu Picchu. Be sure to allow time to visit the Inca Museum in Cusco as well.",
      to:'12/14/2075',
      from:'5/27/2046',
    },
    {
      id: '3',
      name: "Great Pyramid of Giza",
      location: "Giza, Egypt",
      rating: '4.7',
      price: '15',
      image:
        "https://picsum.photos/id/4/800/600",
      photos:[
        "https://picsum.photos/id/4/800/600",
        "https://picsum.photos/id/4/800/600",
        "https://picsum.photos/id/4/800/600",
        "https://picsum.photos/id/4/800/600",
      ],
      tripPlan:
        "Spend a day exploring the Giza pyramid complex, including the Great Pyramid, the Sphinx, and the Valley Temple. Consider taking a camel ride or booking a tour to learn more about the history and significance of these ancient structures.",
      to:'6/21/2079',
      from:'6/26/2042',
    },
    {
      id: '4',
      name: "Taj Mahal",
      location: "Agra, India",
      rating: '4.8',
      price: '20',
      image:
        "https://picsum.photos/id/5/800/600",
      photos:[
        "https://picsum.photos/id/5/800/600",
        "https://picsum.photos/id/5/800/600",
        "https://picsum.photos/id/5/800/600",
        "https://picsum.photos/id/5/800/600",
      ],
      tripPlan:
        "Spend a day in Agra visiting the Taj Mahal, the Agra Fort, and the Tomb of Itimad-ud-Daulah. Consider taking a day trip to the nearby city of Fatehpur Sikri, another important Mughal-era site.",
      to:'6/27/2086',
      from:'5/5/2109',
    },
    {
      id: '5',
      name: "Grand Canyon",
      location: "Arizona, USA",
      rating: '4.9',
      price: '35',
      image:
        "https://picsum.photos/id/6/800/600",
      photos:[
        "https://picsum.photos/id/6/800/600",
        "https://picsum.photos/id/6/800/600",
        "https://picsum.photos/id/6/800/600",
        "https://picsum.photos/id/6/800/600",
      ],
      tripPlan:
        "Spend 2-3 days exploring the Grand Canyon, including hiking along the rim or into the canyon, taking a scenic drive along the South Rim, and visiting the historic Grand Canyon Village. Consider also visiting nearby Horseshoe Bend and Antelope Canyon to see more of the stunning natural landscapes in the area.",
      to:'7/29/2044',
      from:'8/6/2048',
    },
    {
      id: '6',
      name: "Great Barrier Reef",
      location: "Queensland, Australia",
      rating: '4.7',
      price: '150',
      image:
        "https://picsum.photos/id/7/800/600",
      photos:[
        "https://picsum.photos/id/7/800/600",
        "https://picsum.photos/id/7/800/600",
        "https://picsum.photos/id/7/800/600",
        "https://picsum.photos/id/7/800/600",
      ],
      tripPlan:
        "Spend 3-5 days exploring the Great Barrier Reef, including taking a boat tour to see the reef up close, going snorkeling or diving, and visiting the Whitsunday Islands. Consider also spending time in Cairns or Port Douglas, which serve as gateways to the reef.",
      to:'10/7/2123',
      from:'4/3/2069',
    },
    {
      id: '7',
      name: "Sagrada Familia",
      location: "Barcelona, Spain",
      rating: '4.8',
      price: '30',
      image:
        "https://picsum.photos/id/8/800/600",
      photos:[
        "https://picsum.photos/id/8/800/600",
        "https://picsum.photos/id/8/800/600",
        "https://picsum.photos/id/8/800/600",
        "https://picsum.photos/id/8/800/600",
      ],
      tripPlan:
        "Spend a day in Barcelona visiting the Sagrada Familia, as well as other Gaudí-designed landmarks like Park Güell and Casa Batlló. Consider also exploring the historic Gothic Quarter and strolling along La Rambla, the city's famous tree-lined pedestrian mall.",
      to:'12/23/2046',
      from:'1/25/2100',
    },
    {
      id: '8',
      name: "Chichen Itza",
      location: "Yucatan, Mexico",
      rating: '4.7',
      price: '18',
      image:
        "https://picsum.photos/id/13/800/600",
      photos:[
        "https://picsum.photos/id/13/800/600",
        "https://picsum.photos/id/13/800/600",
        "https://picsum.photos/id/13/800/600",
        "https://picsum.photos/id/13/800/600",
      ],
      tripPlan:
        "Spend a day exploring the Chichen Itza archaeological site, including the iconic El Castillo pyramid, the Great Ball Court, and the Temple of Warriors. Consider also visiting the nearby Cenote Ik Kil, a natural sinkhole that was an important source of water for the Mayans.",
      to:'5/17/2096',
      from:'9/30/2109',
    },
    {
      id: '9',
      name: "Colosseum",
      location: "Rome, Italy",
      rating: '4.8',
      price: '22',
      image:
        "https://picsum.photos/id/14/800/600",
      photos:[
        "https://picsum.photos/id/14/800/600",
        "https://picsum.photos/id/14/800/600",
        "https://picsum.photos/id/14/800/600",
        "https://picsum.photos/id/14/800/600",
      ],
      tripPlan:
        "Spend a day exploring the Colosseum and the surrounding Roman Forum and Palatine Hill. Consider also visiting other iconic landmarks in Rome such as the Trevi Fountain, the Pantheon, and St. Peter's Basilica in the Vatican City.",
      to:'7/3/2112',
      from:'6/16/2058',
    },
    {
      id: '10',
      name: "Petra",
      location: "Ma'an Governorate, Jordan",
      rating: '4.9',
      price: '70',
      image:
        "https://picsum.photos/id/15/800/600",
      photos:[
        "https://picsum.photos/id/15/800/600",
        "https://picsum.photos/id/15/800/600",
        "https://picsum.photos/id/15/800/600",
        "https://picsum.photos/id/15/800/600",
      ],
      tripPlan:
        "Spend 2-3 days exploring the ancient city of Petra, including hiking through the Siq, the narrow gorge that serves as the main entrance, and visiting iconic landmarks like the Treasury, the Monastery, and the High Place of Sacrifice. Consider also taking a day trip to the nearby Wadi Rum desert for a unique desert experience.",
      to:'5/19/2095',
      from:'7/7/2026',
    },
  ];


  export const Hotels = [
    {
      id: "hotel1",
      name: "Hotel Grand",
      location: "New York City",
      rating: 4.5,
      adultPrice: 150,
      childPrice: 75,
      image: "https://example.com/hotel1.jpg",
      photos: ["https://example.com/hotel1-photo1.jpg", "https://example.com/hotel1-photo2.jpg", "https://example.com/hotel1-photo3.jpg"],
      description: "Enjoy a luxurious stay in the heart of New York City at Hotel Grand. Our modern amenities and attentive service will make your visit unforgettable.",
      favourites: []
    },
    {
      id: "hotel2",
      name: "Coastal Retreat",
      location: "Malibu, California",
      rating: 4.8,
      adultPrice: 200,
      childPrice: 100,
      image: "https://example.com/hotel2.jpg",
      photos: ["https://example.com/hotel2-photo1.jpg", "https://example.com/hotel2-photo2.jpg", "https://example.com/hotel2-photo3.jpg"],
      description: "Experience the tranquility of the Pacific Ocean at our Coastal Retreat in Malibu. Relax in our comfortable rooms and enjoy breathtaking views.",
      favourites: []
    },
    {
      id: "hotel3",
      name: "Mountain Chalet",
      location: "Aspen, Colorado",
      rating: 4.2,
      adultPrice: 180,
      childPrice: 90,
      image: "https://example.com/hotel3.jpg",
      photos: ["https://example.com/hotel3-photo1.jpg", "https://example.com/hotel3-photo2.jpg", "https://example.com/hotel3-photo3.jpg"],
      description: "Escape to the serene beauty of the Rockies at our Mountain Chalet in Aspen. Enjoy cozy accommodations and easy access to world-class skiing.",
      favourites: []
    },
    {
      id: "hotel4",
      name: "Tropical Oasis",
      location: "Maui, Hawaii",
      rating: 4.7,
      adultPrice: 225,
      childPrice: 115,
      image: "https://example.com/hotel4.jpg",
      photos: ["https://example.com/hotel4-photo1.jpg", "https://example.com/hotel4-photo2.jpg", "https://example.com/hotel4-photo3.jpg"],
      description: "Immerse yourself in the beauty of Maui at our Tropical Oasis. Relax on the beach, explore the island, and indulge in our luxurious amenities.",
      favourites: []
    },
    {
      id: "hotel5",
      name: "Urban Retreat",
      location: "Chicago, Illinois",
      rating: 4.1,
      adultPrice: 160,
      childPrice: 80,
      image: "https://example.com/hotel5.jpg",
      photos: ["https://example.com/hotel5-photo1.jpg", "https://example.com/hotel5-photo2.jpg", "https://example.com/hotel5-photo3.jpg"],
      description: "Discover the vibrant city of Chicago from the comfort of our Urban Retreat. Enjoy modern accommodations and easy access to top attractions.",
      favourites: []
    },
    {
      id: "hotel6",
      name: "Lakeside Getaway",
      location: "Lake Tahoe, California",
      rating: 4.6,
      adultPrice: 190,
      childPrice: 95,
      image: "https://example.com/hotel6.jpg",
      photos: ["https://example.com/hotel6-photo1.jpg", "https://example.com/hotel6-photo2.jpg", "https://example.com/hotel6-photo3.jpg"],
      description: "Escape to the serene beauty of Lake Tahoe at our Lakeside Getaway. Enjoy breathtaking views, outdoor activities, and cozy accommodations.",
      favourites: []
    },
    {
      id: "hotel7",
      name: "Historic Charm",
      location: "Savannah, Georgia",
      rating: 4.4,
      adultPrice: 170,
      childPrice: 85,
      image: "https://example.com/hotel7.jpg",
      photos: ["https://example.com/hotel7-photo1.jpg", "https://example.com/hotel7-photo2.jpg", "https://example.com/hotel7-photo3.jpg"],
      description: "Experience the captivating history and charm of Savannah at our Historic Charm hotel. Immerse yourself in the city's unique culture and hospitality.",
      favourites: []
    },
    {
      id: "hotel8",
      name: "Desert Oasis",
      location: "Scottsdale, Arizona",
      rating: 4.3,
      adultPrice: 185,
      childPrice: 92,
      image: "https://example.com/hotel8.jpg",
      photos: ["https://example.com/hotel8-photo1.jpg", "https://example.com/hotel8-photo2.jpg", "https://example.com/hotel8-photo3.jpg"],
      description: "Escape to the tranquility of the desert at our Desert Oasis in Scottsdale. Enjoy luxurious amenities, stunning landscapes, and a relaxing atmosphere.",
      favourites: []
    },
    {
      id: "hotel9",
      name: "Coastal Escape",
      location: "Cannon Beach, Oregon",
      rating: 4.5,
      adultPrice: 155,
      childPrice: 77,
      image: "https://example.com/hotel9.jpg",
      photos: ["https://example.com/hotel9-photo1.jpg", "https://example.com/hotel9-photo2.jpg", "https://example.com/hotel9-photo3.jpg"],
      description: "Experience the serene beauty of the Oregon coast at our Coastal Escape in Cannon Beach. Enjoy breathtaking ocean views and a tranquil atmosphere.",
      favourites: []
    },
    {
      id: "hotel10",
      name: "City Luxury",
      location: "Seattle, Washington",
      rating: 4.2,
      adultPrice: 180,
      childPrice: 90,
      image: "https://example.com/hotel10.jpg",
      photos: ["https://example.com/hotel10-photo1.jpg", "https://example.com/hotel10-photo2.jpg", "https://example.com/hotel10-photo3.jpg"],
      description: "Discover the vibrant city of Seattle from the comfort of our City Luxury hotel. Enjoy modern amenities, stunning views, and easy access to top attractions.",
      favourites: []
    },
    {
      id: "hotel11",
      name: "Mountain Retreat",
      location: "Whistler, British Columbia",
      rating: 4.6,
      adultPrice: 195,
      childPrice: 97,
      image: "https://example.com/hotel11.jpg",
      photos: ["https://example.com/hotel11-photo1.jpg", "https://example.com/hotel11-photo2.jpg", "https://example.com/hotel11-photo3.jpg"],
      description: "Escape to the breathtaking mountains of Whistler at our Mountain Retreat. Enjoy cozy accommodations, world-class skiing, and stunning natural beauty.",
      favourites: []
    },
    {
      id: "hotel12",
      name: "Beachfront Bliss",
      location: "Miami Beach, Florida",
      rating: 4.7,
      adultPrice: 210,
      childPrice: 105,
      image: "https://example.com/hotel12.jpg",
      photos: ["https://example.com/hotel12-photo1.jpg", "https://example.com/hotel12-photo2.jpg", "https://example.com/hotel12-photo3.jpg"],
      description: "Experience the vibrant energy of Miami Beach at our Beachfront Bliss hotel. Enjoy direct access to the beach, luxurious amenities, and a lively atmosphere.",
      favourites: []
    },
    {
      id: "hotel13",
      name: "Historic Elegance",
      location: "Charleston, South Carolina",
      rating: 4.4,
      adultPrice: 175,
      childPrice: 87,
      image: "https://example.com/hotel13.jpg",
      photos: ["https://example.com/hotel13-photo1.jpg", "https://example.com/hotel13-photo2.jpg", "https://example.com/hotel13-photo3.jpg"],
      description: "Immerse yourself in the historic charm of Charleston at our Historic Elegance hotel. Enjoy luxurious accommodations and easy access to the city's rich cultural attractions.",
      favourites: []
    },
    {
      id: "hotel14",
      name: "Alpine Escape",
      location: "Banff, Alberta",
      rating: 4.8,
      adultPrice: 220,
      childPrice: 110,
      image: "https://example.com/hotel14.jpg",
      photos: ["https://example.com/hotel14-photo1.jpg", "https://example.com/hotel14-photo2.jpg", "https://example.com/hotel14-photo3.jpg"],
      description: "Discover the breathtaking beauty of the Canadian Rockies at our Alpine Escape in Banff. Enjoy cozy accommodations, stunning mountain views, and endless outdoor adventures.",
      favourites: []
    },
    {
      id: "hotel15",
      name: "Coastal Charm",
      location: "Monterey, California",
      rating: 4.3,
      adultPrice: 165,
      childPrice: 82,
      image: "https://example.com/hotel15.jpg",
      photos: ["https://example.com/hotel15-photo1.jpg", "https://example.com/hotel15-photo2.jpg", "https://example.com/hotel15-photo3.jpg"],
      description: "Experience the captivating coastal charm of Monterey at our Coastal Charm hotel. Enjoy breathtaking ocean views, rich history, and a relaxing atmosphere.",
      favourites: []
    },
    {
      id: "hotel16",
      name: "Vineyard Retreat",
      location: "Napa Valley, California",
      rating: 4.9,
      adultPrice: 235,
      childPrice: 117,
      image: "https://example.com/hotel16.jpg",
      photos: ["https://example.com/hotel16-photo1.jpg", "https://example.com/hotel16-photo2.jpg", "https://example.com/hotel16-photo3.jpg"],
      description: "Immerse yourself in the beauty of Napa Valley at our Vineyard Retreat. Enjoy luxurious accommodations, world-class wine tasting, and stunning natural surroundings.",
      favourites: []
    },
    {
      id: "hotel17",
      name: "Urban Oasis",
      location: "San Francisco, California",
      rating: 4.5,
      adultPrice: 190,
      childPrice: 95,
      image: "https://example.com/hotel17.jpg",
      photos: ["https://example.com/hotel17-photo1.jpg", "https://example.com/hotel17-photo2.jpg", "https://example.com/hotel17-photo3.jpg"],
      description: "Discover the vibrant city of San Francisco from the comfort of our Urban Oasis hotel. Enjoy modern amenities, stunning views, and easy access to top attractions.",
      favourites: []
    },
    {
      id: "hotel18",
      name: "Coastal Retreat",
      location: "Carmel-by-the-Sea, California",
      rating: 4.7,
      adultPrice: 205,
      childPrice: 102,
      image: "https://example.com/hotel18.jpg",
      photos: ["https://example.com/hotel18-photo1.jpg", "https://example.com/hotel18-photo2.jpg", "https://example.com/hotel18-photo3.jpg"],
      description: "Experience the serene beauty of the California coast at our Coastal Retreat in Carmel-by-the-Sea. Enjoy breathtaking ocean views, cozy accommodations, and a relaxing atmosphere.",
      favourites: []
    },
    {
      id: "hotel19",
      name: "Mountain Lodge",
      location: "Park City, Utah",
      rating: 4.6,
      adultPrice: 200,
      childPrice: 100,
      image: "https://example.com/hotel19.jpg",
      photos: ["https://example.com/hotel19-photo1.jpg", "https://example.com/hotel19-photo2.jpg", "https://example.com/hotel19-photo3.jpg"],
      description: "Escape to the majestic mountains of Park City at our Mountain Lodge. Enjoy cozy accommodations, world-class skiing, and stunning natural beauty.",
      favourites: []
    },
    {
      id: "hotel20",
      name: "Tropical Oasis",
      location: "Kona, Hawaii",
      rating: 4.8,
      adultPrice: 230,
      childPrice: 115,
      image: "https://example.com/hotel20.jpg",
      photos: ["https://example.com/hotel20-photo1.jpg", "https://example.com/hotel20-photo2.jpg", "https://example.com/hotel20-photo3.jpg"],
      description: "Immerse yourself in the beauty of Hawaii at our Tropical Oasis in Kona. Relax on the beach, explore the island, and indulge in our luxurious amenities.",
      favourites: []
    }
  ];



  export const AirLines = [
    {
      id: 'flight1',
      name: 'Flight to London',
      type: 'Single Way',
      price: 500.99,
      departure: 'New York',
      departureTimestamps: '2024-07-01T10:00:00',
      arrival: 'London',
      arrivalTimestamps: '2024-07-01T18:00:00',
      secondArrival: '',
      secondArrivalTimestamps: '',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight1.jpg',
      description: 'Non-stop flight from New York to London.'
    },
    {
      id: 'flight2',
      name: 'Round Trip to Paris',
      type: 'Round Trip',
      price: 800.50,
      departure: 'Chicago',
      departureTimestamps: '2024-08-15T08:30:00',
      arrival: 'Paris',
      arrivalTimestamps: '2024-08-15T16:30:00',
      secondArrival: 'Chicago',
      secondArrivalTimestamps: '2024-08-22T12:00:00',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: 'Paris',
      retturnTimestamps: '2024-08-22T09:00:00',
      image: 'https://example.com/flight2.jpg',
      description: 'Round trip flight from Chicago to Paris with a return date.'
    },
    {
      id: 'flight3',
      name: 'Multicity Trip',
      type: 'Multicity',
      price: 1200.75,
      departure: 'Los Angeles',
      departureTimestamps: '2024-09-10T07:45:00',
      arrival: 'Tokyo',
      arrivalTimestamps: '2024-09-11T05:00:00',
      secondArrival: 'Singapore',
      secondArrivalTimestamps: '2024-09-14T11:30:00',
      thirdArrival: 'Los Angeles',
      thirdArrivalTimestamps: '2024-09-18T18:15:00',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight3.jpg',
      description: 'Multicity trip from Los Angeles to Tokyo, Singapore, and back to Los Angeles.'
    },
    {
      id: 'flight4',
      name: 'Single Way to Miami',
      type: 'Single Way',
      price: 350.25,
      departure: 'Atlanta',
      departureTimestamps: '2024-10-01T14:20:00',
      arrival: 'Miami',
      arrivalTimestamps: '2024-10-01T16:10:00',
      secondArrival: '',
      secondArrivalTimestamps: '',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight4.jpg',
      description: 'Non-stop flight from Atlanta to Miami.'
    },
    {
      id: 'flight5',
      name: 'Round Trip to Seattle',
      type: 'Round Trip',
      price: 600.75,
      departure: 'Denver',
      departureTimestamps: '2024-11-05T06:00:00',
      arrival: 'Seattle',
      arrivalTimestamps: '2024-11-05T08:30:00',
      secondArrival: 'Denver',
      secondArrivalTimestamps: '2024-11-12T15:45:00',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: 'Seattle',
      retturnTimestamps: '2024-11-12T12:00:00',
      image: 'https://example.com/flight5.jpg',
      description: 'Round trip flight from Denver to Seattle with a return date.'
    },
    {
      id: 'flight6',
      name: 'Multicity Trip',
      type: 'Multicity',
      price: 1500.00,
      departure: 'Dallas',
      departureTimestamps: '2024-12-01T09:15:00',
      arrival: 'London',
      arrivalTimestamps: '2024-12-02T06:45:00',
      secondArrival: 'Paris',
      secondArrivalTimestamps: '2024-12-05T11:00:00',
      thirdArrival: 'Dallas',
      thirdArrivalTimestamps: '2024-12-10T18:30:00',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight6.jpg',
      description: 'Multicity trip from Dallas to London, Paris, and back to Dallas.'
    },
    {
      id: 'flight7',
      name: 'Single Way to San Francisco',
      type: 'Single Way',
      price: 425.99,
      departure: 'New York',
      departureTimestamps: '2024-01-15T11:00:00',
      arrival: 'San Francisco',
      arrivalTimestamps: '2024-01-15T14:30:00',
      secondArrival: '',
      secondArrivalTimestamps: '',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight7.jpg',
      description: 'Non-stop flight from New York to San Francisco.'
    },
    {
      id: 'flight8',
      name: 'Round Trip to Chicago',
      type: 'Round Trip',
      price: 550.25,
      departure: 'Miami',
      departureTimestamps: '2024-02-20T08:00:00',
      arrival: 'Chicago',
      arrivalTimestamps: '2024-02-20T10:45:00',
      secondArrival: 'Miami',
      secondArrivalTimestamps: '2024-02-27T17:30:00',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: 'Chicago',
      retturnTimestamps: '2024-02-27T14:00:00',
      image: 'https://example.com/flight8.jpg',
      description: 'Round trip flight from Miami to Chicago with a return date.'
    },
    {
      id: 'flight9',
      name: 'Multicity Trip',
      type: 'Multicity',
      price: 1800.50,
      departure: 'Houston',
      departureTimestamps: '2024-03-01T06:30:00',
      arrival: 'Tokyo',
      arrivalTimestamps: '2024-03-02T12:15:00',
      secondArrival: 'Hong Kong',
      secondArrivalTimestamps: '2024-03-06T08:45:00',
      thirdArrival: 'Houston',
      thirdArrivalTimestamps: '2024-03-12T19:00:00',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight9.jpg',
      description: 'Multicity trip from Houston to Tokyo, Hong Kong, and back to Houston.'
    },
    {
      id: 'flight10',
      name: 'Single Way to Washington, D.C.',
      type: 'Single Way',
      price: 375.75,
      departure: 'Philadelphia',
      departureTimestamps: '2024-04-05T13:30:00',
      arrival: 'Washington, D.C.',
      arrivalTimestamps: '2024-04-05T14:45:00',
      secondArrival: '',
      secondArrivalTimestamps: '',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight10.jpg',
      description: 'Non-stop flight from Philadelphia to Washington, D.C.'
    },
    {
      id: 'flight11',
      name: 'Round Trip to Las Vegas',
      type: 'Round Trip',
      price: 650.00,
      departure: 'Portland',
      departureTimestamps: '2024-05-01T08:00:00',
      arrival: 'Las Vegas',
      arrivalTimestamps: '2024-05-01T10:30:00',
      secondArrival: 'Portland',
      secondArrivalTimestamps: '2024-05-08T18:15:00',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: 'Las Vegas',
      retturnTimestamps: '2024-05-08T15:00:00',
      image: 'https://example.com/flight11.jpg',
      description: 'Round trip flight from Portland to Las Vegas with a return date.'
    },
    {
      id: 'flight12',
      name: 'Multicity Trip',
      type: 'Multicity',
      price: 2000.00,
      departure: 'San Francisco',
      departureTimestamps: '2024-06-15T07:00:00',
      arrival: 'London',
      arrivalTimestamps: '2024-06-16T11:45:00',
      secondArrival: 'Paris',
      secondArrivalTimestamps: '2024-06-19T13:30:00',
      thirdArrival: 'San Francisco',
      thirdArrivalTimestamps: '2024-06-24T20:00:00',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight12.jpg',
      description: 'Multicity trip from San Francisco to London, Paris, and back to San Francisco.'
    },
    {
      id: 'flight13',
      name: 'Single Way to Denver',
      type: 'Single Way',
      price: 325.50,
      departure: 'Chicago',
      departureTimestamps: '2024-07-01T15:20:00',
      arrival: 'Denver',
      arrivalTimestamps: '2024-07-01T17:00:00',
      secondArrival: '',
      secondArrivalTimestamps: '',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight13.jpg',
      description: 'Non-stop flight from Chicago to Denver.'
    },
    {
      id: 'flight14',
      name: 'Round Trip to Orlando',
      type: 'Round Trip',
      price: 575.25,
      departure: 'New York',
      departureTimestamps: '2024-08-10T09:00:00',
      arrival: 'Orlando',
      arrivalTimestamps: '2024-08-10T11:30:00',
      secondArrival: 'New York',
      secondArrivalTimestamps: '2024-08-17T17:45:00',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: 'Orlando',
      retturnTimestamps: '2024-08-17T14:00:00',
      image: 'https://example.com/flight14.jpg',
      description: 'Round trip flight from New York to Orlando with a return date.'
    },
    {
      id: 'flight15',
      name: 'Multicity Trip',
      type: 'Multicity',
      price: 1900.75,
      departure: 'Atlanta',
      departureTimestamps: '2024-09-01T06:45:00',
      arrival: 'Rome',
      arrivalTimestamps: '2024-09-02T12:15:00',
      secondArrival: 'Madrid',
      secondArrivalTimestamps: '2024-09-06T09:30:00',
      thirdArrival: 'Atlanta',
      thirdArrivalTimestamps: '2024-09-12T18:00:00',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight15.jpg',
      description: 'Multicity trip from Atlanta to Rome, Madrid, and back to Atlanta.'
    },
    {
      id: 'flight16',
      name: 'Single Way to Nashville',
      type: 'Single Way',
      price: 275.75,
      departure: 'Indianapolis',
      departureTimestamps: '2024-10-15T14:00:00',
      arrival: 'Nashville',
      arrivalTimestamps: '2024-10-15T15:30:00',
      secondArrival: '',
      secondArrivalTimestamps: '',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight16.jpg',
      description: 'Non-stop flight from Indianapolis to Nashville.'
    },
    {
      id: 'flight17',
      name: 'Round Trip to Seattle',
      type: 'Round Trip',
      price: 625.50,
      departure: 'Los Angeles',
      departureTimestamps: '2024-11-20T08:00:00',
      arrival: 'Seattle',
      arrivalTimestamps: '2024-11-20T10:30:00',
      secondArrival: 'Los Angeles',
      secondArrivalTimestamps: '2024-11-27T17:15:00',
      thirdArrival: '',
      thirdArrivalTimestamps: '',
      retturn: 'Seattle',
      retturnTimestamps: '2024-11-27T14:00:00',
      image: 'https://example.com/flight17.jpg',
      description: 'Round trip flight from Los Angeles to Seattle with a return date.'
    },
    {
      id: 'flight18',
      name: 'Multicity Trip',
      type: 'Multicity',
      price: 2100.00,
      departure: 'New York',
      departureTimestamps: '2024-12-01T10:00:00',
      arrival: 'Paris',
      arrivalTimestamps: '2024-12-02T09:30:00',
      secondArrival: 'Rome',
      secondArrivalTimestamps: '2024-12-06T11:45:00',
      thirdArrival: 'New York',
      thirdArrivalTimestamps: '2024-12-12T19:00:00',
      retturn: '',
      retturnTimestamps: '',
      image: 'https://example.com/flight18.jpg',
      description: 'Multicity trip from New York to Paris, Rome, and back to New York.'
    },
  ];