export const TourData = [
    {
      id: '1',
      description: 'Explore the ancient ruins of Machu Picchu',
      title: 'Machu Picchu Tour',
      productId: 'MP001',
      mode: 'Tour',
      status: 'Pending',
      timestamp: '2023-06-01T12:00:00Z',
      image: 'https://example.com/machu-picchu.jpg',
      email: 'john.doe@example.com',
      name: 'John Doe',
      phone: '+1 (555) 123-4567',
      passportNumber: 'AB123456'
    },
    {
      id: '2',
      description: 'Discover the vibrant culture of Tokyo',
      title: 'Tokyo City Tour',
      productId: 'TC001',
      mode: 'Tour',
      status: 'Approved',
      timestamp: '2023-07-15T10:30:00Z',
      image: 'https://example.com/tokyo.jpg',
      email: 'jane.smith@example.com',
      name: 'Jane Smith',
      phone: '+1 (555) 987-6543',
      passportNumber: 'CD789012'
    },
    {
      id: '3',
      description: 'Explore the natural wonders of Yellowstone National Park',
      title: 'Yellowstone Adventure',
      productId: 'YS001',
      mode: 'Tour',
      status: 'Cancelled',
      timestamp: '2023-08-20T15:45:00Z',
      image: 'https://example.com/yellowstone.jpg',
      email: 'bob.johnson@example.com',
      name: 'Bob Johnson',
      phone: '+1 (555) 246-8013',
      passportNumber: 'EF345678'
    },
    {
      id: '4',
      description: 'Discover the history and culture of Rome',
      title: 'Rome City Tour',
      productId: 'RC001',
      mode: 'Tour',
      status: 'Pending',
      timestamp: '2023-09-01T09:00:00Z',
      image: 'https://example.com/rome.jpg',
      email: 'alice.brown@example.com',
      name: 'Alice Brown',
      phone: '+1 (555) 369-2580',
      passportNumber: 'GH901234'
    },
    {
      id: '5',
      description: 'Explore the natural beauty of the Canadian Rockies',
      title: 'Banff National Park Tour',
      productId: 'BN001',
      mode: 'Tour',
      status: 'Approved',
      timestamp: '2023-10-10T13:20:00Z',
      image: 'https://example.com/banff.jpg',
      email: 'david.lee@example.com',
      name: 'David Lee',
      phone: '+1 (555) 753-1902',
      passportNumber: 'IJ567890'
    },
    {
      id: '6',
      description: 'Explore the vibrant street art and nightlife of Berlin',
      title: 'Berlin City Tour',
      productId: 'BC001',
      mode: 'Tour',
      status: 'Cancelled',
      timestamp: '2023-11-15T18:00:00Z',
      image: 'https://example.com/berlin.jpg',
      email: 'sarah.williams@example.com',
      name: 'Sarah Williams',
      phone: '+1 (555) 159-4623',
      passportNumber: 'KL234567'
    },
    {
      id: '7',
      description: 'Discover the natural wonders of Iceland',
      title: 'Iceland Adventure',
      productId: 'IC001',
      mode: 'Tour',
      status: 'Pending',
      timestamp: '2023-12-01T11:30:00Z',
      image: 'https://example.com/iceland.jpg',
      email: 'michael.wilson@example.com',
      name: 'Michael Wilson',
      phone: '+1 (555) 802-9135',
      passportNumber: 'MN901234'
    },
    {
      id: '8',
      description: 'Explore the ancient temples and vibrant markets of Bali',
      title: 'Bali Cultural Tour',
      productId: 'BC002',
      mode: 'Tour',
      status: 'Approved',
      timestamp: '2024-01-05T14:45:00Z',
      image: 'https://example.com/bali.jpg',
      email: 'emily.davis@example.com',
      name: 'Emily Davis',
      phone: '+1 (555) 425-7912',
      passportNumber: 'OP567890'
    },
    {
      id: '9',
      description: 'Experience the natural beauty and wildlife of the Galapagos Islands',
      title: 'Galapagos Islands Tour',
      productId: 'GI001',
      mode: 'Tour',
      status: 'Cancelled',
      timestamp: '2024-02-15T16:00:00Z',
      image: 'https://example.com/galapagos.jpg',
      email: 'daniel.martinez@example.com',
      name: 'Daniel Martinez',
      phone: '+1 (555) 638-2094',
      passportNumber: 'QR234567'
    },
    {
      id: '10',
      description: 'Explore the rich history and culture of Egypt',
      title: 'Egypt Historical Tour',
      productId: 'EH001',
      mode: 'Tour',
      status: 'Pending',
      timestamp: '2024-03-01T08:30:00Z',
      image: 'https://example.com/egypt.jpg',
      email: 'olivia.gonzalez@example.com',
      name: 'Olivia Gonzalez',
      phone: '+1 (555) 971-3256',
      passportNumber: 'ST901234'
    },
    {
      id: '11',
      description: 'Discover the natural wonders and vibrant cities of New Zealand',
      title: 'New Zealand Adventure',
      productId: 'NZ001',
      mode: 'Tour',
      status: 'Approved',
      timestamp: '2024-04-10T12:00:00Z',
      image: 'https://example.com/new-zealand.jpg',
      email: 'james.lopez@example.com',
      name: 'James Lopez',
      phone: '+1 (555) 284-6710',
      passportNumber: 'UV567890'
    },
    {
      id: '12',
      description: 'Explore the rich culture and stunning landscapes of Peru',
      title: 'Peru Cultural Tour',
      productId: 'PC001',
      mode: 'Tour',
      status: 'Cancelled',
      timestamp: '2024-05-20T15:30:00Z',
      image: 'https://example.com/peru.jpg',
      email: 'sofia.ramirez@example.com',
      name: 'Sofia Ramirez',
      phone: '+1 (555) 539-2817',
      passportNumber: 'WX234567'
    },
    {
      id: '13',
      description: 'Discover the natural wonders and vibrant cities of Australia',
      title: 'Australia Adventure',
      productId: 'AA001',
      mode: 'Tour',
      status: 'Pending',
      timestamp: '2024-06-01T10:00:00Z',
      image: 'https://example.com/australia.jpg',
      email: 'alexander.morales@example.com',
      name: 'Alexander Morales',
      phone: '+1 (555) 691-3452',
      passportNumber: 'YZ901234'
    },
    {
      id: '14',
      description: 'Explore the rich history and culture of Greece',
      title: 'Greece Historical Tour',
      productId: 'GH002',
      mode: 'Tour',
      status: 'Approved',
      timestamp: '2024-07-15T13:45:00Z',
      image: 'https://example.com/greece.jpg',
      email: 'isabella.castillo@example.com',
      name: 'Isabella Castillo',
      phone: '+1 (555) 357-9102',
      passportNumber: 'AB901234'
    },
    {
      id: '15',
      description: 'Discover the vibrant culture and natural beauty of Costa Rica',
      title: 'Costa Rica Adventure',
      productId: 'CR001',
      mode: 'Tour',
      status: 'Cancelled',
      timestamp: '2024-08-01T16:30:00Z',
      image: 'https://example.com/costa-rica.jpg',
      email: 'matthew.garcia@example.com',
      name: 'Matthew Garcia',
      phone: '+1 (555) 814-6329',
      passportNumber: 'CD234567'
    },
    {
      id: '16',
      description: 'Explore the rich history and culture of Japan',
      title: 'Japan Cultural Tour',
      productId: 'JC001',
      mode: 'Tour',
      status: 'Pending',
      timestamp: '2024-09-10T11:00:00Z',
      image: 'https://example.com/japan.jpg',
      email: 'emma.diaz@example.com',
      name: 'Emma Diaz',
      phone: '+1 (555) 472-9085',
      passportNumber: 'EF901234'
    },
    {
      id: '17',
      description: 'Discover the natural wonders and vibrant cities of South Africa',
      title: 'South Africa Adventure',
      productId: 'SA001',
      mode: 'Tour',
      status: 'Approved',
      timestamp: '2024-10-01T14:00:00Z',
      image: 'https://example.com/south-africa.jpg',
      email: 'sebastian.rodriguez@example.com',
      name: 'Sebastian Rodriguez',
      phone: '+1 (555) 629-3417',
      passportNumber: 'GH234567'
    },
    {
      id: '18',
      description: 'Explore the rich history and culture of Morocco',
      title: 'Morocco Cultural Tour',
      productId: 'MC001',
      mode: 'Tour',
      status: 'Cancelled',
      timestamp: '2024-11-15T09:30:00Z',
      image: 'https://example.com/morocco.jpg',
      email: 'gabriela.hernandez@example.com',
      name: 'Gabriela Hernandez',
      phone: '+1 (555) 793-2568',
      passportNumber: 'IJ901234'
    },
    {
      id: '19',
      description: 'Discover the natural wonders and vibrant culture of Vietnam',
      title: 'Vietnam Adventure',
      productId: 'VA001',
      mode: 'Tour',
      status: 'Pending',
      timestamp: '2024-12-01T15:00:00Z',
      image: 'https://example.com/vietnam.jpg',
      email: 'lucas.torres@example.com',
      name: 'Lucas Torres',
      phone: '+1 (555) 452-9630',
      passportNumber: 'KL234567'
    },
    {
      id: '20',
      description: 'Explore the rich history and culture of India',
      title: 'India Cultural Tour',
      productId: 'IC002',
      mode: 'Tour',
      status: 'Approved',
      timestamp: '2025-01-05T12:00:00Z',
      image: 'https://example.com/india.jpg',
      email: 'olivia.sanchez@example.com',
      name: 'Olivia Sanchez',
      phone: '+1 (555) 718-3905',
      passportNumber: 'MN901234'
    }
  ];



  export const HotelData =[
    {
      id: '1',
      description: 'Cozy hotel in the heart of the city',
      title: 'Downtown Hotel',
      productId: 'p001',
      mode: 'Hotel',
      status: 'Pending',
      checkinDate: '2023-08-15',
      checkoutDate: '2023-08-20',
      image: 'https://example.com/hotel1.jpg',
      email: 'info@downtownhotel.com',
      name: 'Downtown Hotel',
      phone: '+1 555-1234',
      adults: 2,
      children: 1,
      price: '150.00'
    },
    {
      id: '2',
      description: 'Luxurious beachfront resort with stunning views',
      title: 'Oceanview Resort',
      productId: 'p002',
      mode: 'Hotel',
      status: 'Approved',
      checkinDate: '2023-09-01',
      checkoutDate: '2023-09-08',
      image: 'https://example.com/hotel2.jpg',
      email: 'reservations@oceanviewresort.com',
      name: 'Oceanview Resort',
      phone: '+1 555-5678',
      adults: 2,
      children: 0,
      price: '300.00'
    },
    {
      id: '3',
      description: 'Charming boutique hotel with a cozy atmosphere',
      title: 'Boutique Hotel',
      productId: 'p003',
      mode: 'Hotel',
      status: 'Cancelled',
      checkinDate: '2023-10-01',
      checkoutDate: '2023-10-05',
      image: 'https://example.com/hotel3.jpg',
      email: 'info@boutiquehotel.com',
      name: 'Boutique Hotel',
      phone: '+1 555-9012',
      adults: 1,
      children: 0,
      price: '120.00'
    },
    {
      id: '4',
      description: 'Modern hotel with excellent amenities and service',
      title: 'City Center Hotel',
      productId: 'p004',
      mode: 'Hotel',
      status: 'Pending',
      checkinDate: '2023-11-10',
      checkoutDate: '2023-11-15',
      image: 'https://example.com/hotel4.jpg',
      email: 'reservations@citycenterhotel.com',
      name: 'City Center Hotel',
      phone: '+1 555-3456',
      adults: 2,
      children: 2,
      price: '200.00'
    },
    {
      id: '5',
      description: 'Scenic mountain resort with breathtaking views',
      title: 'Mountain Retreat',
      productId: 'p005',
      mode: 'Hotel',
      status: 'Approved',
      checkinDate: '2023-12-01',
      checkoutDate: '2023-12-07',
      image: 'https://example.com/hotel5.jpg',
      email: 'info@mountainretreat.com',
      name: 'Mountain Retreat',
      phone: '+1 555-7890',
      adults: 3,
      children: 1,
      price: '250.00'
    },
    {
      id: '6',
      description: 'Cozy cabin in the woods for a peaceful getaway',
      title: 'Woodland Cabin',
      productId: 'p006',
      mode: 'Hotel',
      status: 'Cancelled',
      checkinDate: '2024-01-01',
      checkoutDate: '2024-01-05',
      image: 'https://example.com/hotel6.jpg',
      email: 'reservations@woodlandcabin.com',
      name: 'Woodland Cabin',
      phone: '+1 555-2109',
      adults: 2,
      children: 0,
      price: '180.00'
    },
    {
      id: '7',
      description: 'Elegant hotel with a historic charm',
      title: 'Vintage Hotel',
      productId: 'p007',
      mode: 'Hotel',
      status: 'Pending',
      checkinDate: '2024-02-15',
      checkoutDate: '2024-02-20',
      image: 'https://example.com/hotel7.jpg',
      email: 'info@vintagehotel.com',
      name: 'Vintage Hotel',
      phone: '+1 555-6543',
      adults: 2,
      children: 1,
      price: '160.00'
    },
    {
      id: '8',
      description: 'Waterfront resort with a private beach and marina',
      title: 'Seaside Resort',
      productId: 'p008',
      mode: 'Hotel',
      status: 'Approved',
      checkinDate: '2024-03-01',
      checkoutDate: '2024-03-08',
      image: 'https://example.com/hotel8.jpg',
      email: 'reservations@seasideresort.com',
      name: 'Seaside Resort',
      phone: '+1 555-8901',
      adults: 4,
      children: 2,
      price: '350.00'
    },
    {
      id: '9',
      description: 'Rustic cabin retreat for a nature-inspired getaway',
      title: 'Wilderness Cabin',
      productId: 'p009',
      mode: 'Hotel',
      status: 'Cancelled',
      checkinDate: '2024-04-01',
      checkoutDate: '2024-04-05',
      image: 'https://example.com/hotel9.jpg',
      email: 'info@wildernesscabin.com',
      name: 'Wilderness Cabin',
      phone: '+1 555-2345',
      adults: 2,
      children: 0,
      price: '190.00'
    },
    {
      id: '10',
      description: 'Boutique hotel with a focus on sustainability and eco-friendly practices',
      title: 'Green Hotel',
      productId: 'p010',
      mode: 'Hotel',
      status: 'Pending',
      checkinDate: '2024-05-10',
      checkoutDate: '2024-05-15',
      image: 'https://example.com/hotel10.jpg',
      email: 'reservations@greenhotel.com',
      name: 'Green Hotel',
      phone: '+1 555-6789',
      adults: 2,
      children: 1,
      price: '180.00'
    },
    {
      id: '11',
      description: 'Luxury resort with world-class amenities and stunning views',
      title: 'Panorama Resort',
      productId: 'p011',
      mode: 'Hotel',
      status: 'Approved',
      checkinDate: '2024-06-01',
      checkoutDate: '2024-06-07',
      image: 'https://example.com/hotel11.jpg',
      email: 'info@panoramaresort.com',
      name: 'Panorama Resort',
      phone: '+1 555-0123',
      adults: 3,
      children: 2,
      price: '400.00'
    },
    {
      id: '12',
      description: 'Intimate boutique hotel with a focus on personalized service',
      title: 'Boutique Retreat',
      productId: 'p012',
      mode: 'Hotel',
      status: 'Cancelled',
      checkinDate: '2024-07-01',
      checkoutDate: '2024-07-05',
      image: 'https://example.com/hotel12.jpg',
      email: 'reservations@boutiquehotel.com',
      name: 'Boutique Retreat',
      phone: '+1 555-4567',
      adults: 2,
      children: 0,
      price: '220.00'
    },
    {
      id: '13',
      description: 'Waterfront hotel with a private marina and stunning views',
      title: 'Waterfront Hotel',
      productId: 'p013',
      mode: 'Hotel',
      status: 'Pending',
      checkinDate: '2024-08-15',
      checkoutDate: '2024-08-20',
      image: 'https://example.com/hotel13.jpg',
      email: 'info@waterfronthotel.com',
      name: 'Waterfront Hotel',
      phone: '+1 555-8901',
      adults: 2,
      children: 1,
      price: '280.00'
    },
    {
      id: '14',
      description: 'Mountain resort with ski-in/ski-out access and a cozy atmosphere',
      title: 'Ski Resort',
      productId: 'p014',
      mode: 'Hotel',
      status: 'Approved',
      checkinDate: '2024-09-01',
      checkoutDate: '2024-09-08',
      image: 'https://example.com/hotel14.jpg',
      email: 'reservations@skiresort.com',
      name: 'Ski Resort',
      phone: '+1 555-2345',
      adults: 3,
      children: 1,
      price: '320.00'
    },
    {
      id: '15',
      description: 'Historic hotel with charming decor and excellent dining options',
      title: 'Historic Hotel',
      productId: 'p015',
      mode: 'Hotel',
      status: 'Cancelled',
      checkinDate: '2024-10-01',
      checkoutDate: '2024-10-05',
      image: 'https://example.com/hotel15.jpg',
      email: 'info@historichotel.com',
      name: 'Historic Hotel',
      phone: '+1 555-6789',
      adults: 2,
      children: 0,
      price: '200.00'
    },
    {
      id: '16',
      description: 'Peaceful resort in a rural setting, perfect for a relaxing getaway',
      title: 'Country Retreat',
      productId: 'p016',
      mode: 'Hotel',
      status: 'Pending',
      checkinDate: '2024-11-10',
      checkoutDate: '2024-11-15',
      image: 'https://example.com/hotel16.jpg',
      email: 'reservations@countryretreat.com',
      name: 'Country Retreat',
      phone: '+1 555-0123',
      adults: 2,
      children: 2,
      price: '190.00'
    },
    {
      id: '17',
      description: 'Upscale hotel with a focus on wellness and spa treatments',
      title: 'Wellness Hotel',
      productId: 'p017',
      mode: 'Hotel',
      status: 'Approved',
      checkinDate: '2024-12-01',
      checkoutDate: '2024-12-07',
      image: 'https://example.com/hotel17.jpg',
      email: 'info@wellnesshotel.com',
      name: 'Wellness Hotel',
      phone: '+1 555-4567',
      adults: 2,
      children: 1,
      price: '300.00'
    },
    {
      id: '18',
      description: 'Charming bed and breakfast with a cozy, homey atmosphere',
      title: 'Countryside B&B',
      productId: 'p018',
      mode: 'Hotel',
      status: 'Cancelled',
      checkinDate: '2025-01-01',
      checkoutDate: '2025-01-05',
      image: 'https://example.com/hotel18.jpg',
      email: 'reservations@countrysidebb.com',
      name: 'Countryside B&B',
      phone: '+1 555-8901',
      adults: 2,
      children: 0,
      price: '150.00'
    },
    {
      id: '19',
      description: 'Luxury hotel with world-class spa and fitness facilities',
      title: 'Spa Hotel',
      productId: 'p019',
      mode: 'Hotel',
      status: 'Pending',
      checkinDate: '2025-02-15',
      checkoutDate: '2025-02-20',
      image: 'https://example.com/hotel19.jpg',
      email: 'info@spahotel.com',
      name: 'Spa Hotel',
      phone: '+1 555-2345',
      adults: 2,
      children: 1,
      price: '400.00'
    },
    {
      id: '20',
      description: 'Boutique hotel with a focus on art, design, and local culture',
      title: 'Artsy Hotel',
      productId: 'p020',
      mode: 'Hotel',
      status: 'Approved',
      checkinDate: '2025-03-01',
      checkoutDate: '2025-03-08',
      image: 'https://example.com/hotel20.jpg',
      email: 'reservations@artsyhotel.com',
      name: 'Artsy Hotel',
      phone: '+1 555-6789',
      adults: 2,
      children: 0,
      price: '250.00'
    }
  ]


  export const FlightData = [
    {
      id: '1',
      description: 'Flight from New York to Los Angeles',
      title: 'New York to Los Angeles',
      productId: 'flight-001',
      mode: 'Flight',
      type: 'One Way',
      from: 'New York',
      to: 'Los Angeles',
      cities: ['New York', 'Los Angeles'],
      status: 'Pending',
      reurntDepartureDateAndTime: '',
      returnArrivalDateAndTime: '',
      departureDateAndTime: '2023-08-15T09:00:00',
      arrivalDateAndTime: '2023-08-15T12:00:00',
      image: 'https://example.com/flight-image.jpg',
      email: 'john@example.com',
      name: 'John Doe',
      passportNumber: 'ABC12345',
      phone: '555-1234',
      passengers: 1,
      price: '500.00',
      timestamp: '2023-08-01T12:00:00'
    },
    {
      id: '2',
      description: 'Round trip flight from Chicago to Miami',
      title: 'Chicago to Miami Round Trip',
      productId: 'flight-002',
      mode: 'Flight',
      type: 'Round Trip',
      from: 'Chicago',
      to: 'Miami',
      cities: ['Chicago', 'Miami'],
      status: 'Approved',
      reurntDepartureDateAndTime: '2023-08-22T18:00:00',
      returnArrivalDateAndTime: '2023-08-29T21:00:00',
      departureDateAndTime: '2023-08-15T07:00:00',
      arrivalDateAndTime: '2023-08-15T11:00:00',
      image: 'https://example.com/flight-image-2.jpg',
      email: 'jane@example.com',
      name: 'Jane Smith',
      passportNumber: 'XYZ54321',
      phone: '555-5678',
      passengers: 2,
      price: '800.00',
      timestamp: '2023-08-01T12:00:00'
    },
    {
      id: '3',
      description: 'Multicity flight from Seattle to San Francisco to Los Angeles',
      title: 'Seattle to San Francisco to Los Angeles',
      productId: 'flight-003',
      mode: 'Flight',
      type: 'Multicity',
      from: 'Seattle',
      to: 'Los Angeles',
      cities: ['Seattle', 'San Francisco', 'Los Angeles'],
      status: 'Cancelled',
      reurntDepartureDateAndTime: '',
      returnArrivalDateAndTime: '',
      departureDateAndTime: '2023-08-20T06:00:00',
      arrivalDateAndTime: '2023-08-22T18:00:00',
      image: 'https://example.com/flight-image-3.jpg',
      email: 'bob@example.com',
      name: 'Bob Johnson',
      passportNumber: 'DEF98765',
      phone: '555-2468',
      passengers: 3,
      price: '1200.00',
      timestamp: '2023-08-01T12:00:00'
    },
    {
      id: '4',
      description: 'One way flight from London to Paris',
      title: 'London to Paris',
      productId: 'flight-004',
      mode: 'Flight',
      type: 'One Way',
      from: 'London',
      to: 'Paris',
      cities: ['London', 'Paris'],
      status: 'Pending',
      reurntDepartureDateAndTime: '',
      returnArrivalDateAndTime: '',
      departureDateAndTime: '2023-09-01T14:00:00',
      arrivalDateAndTime: '2023-09-01T16:00:00',
      image: 'https://example.com/flight-image-4.jpg',
      email: 'sarah@example.com',
      name: 'Sarah Lee',
      passportNumber: 'GHI67890',
      phone: '555-3690',
      passengers: 1,
      price: '250.00',
      timestamp: '2023-08-01T12:00:00'
    },
    {
      id: '5',
      description: 'Round trip flight from Tokyo to Osaka',
      title: 'Tokyo to Osaka Round Trip',
      productId: 'flight-005',
      mode: 'Flight',
      type: 'Round Trip',
      from: 'Tokyo',
      to: 'Osaka',
      cities: ['Tokyo', 'Osaka'],
      status: 'Approved',
      reurntDepartureDateAndTime: '2023-10-15T20:00:00',
      returnArrivalDateAndTime: '2023-10-22T22:00:00',
      departureDateAndTime: '2023-10-08T08:00:00',
      arrivalDateAndTime: '2023-10-08T10:00:00',
      image: 'https://example.com/flight-image-5.jpg',
      email: 'david@example.com',
      name: 'David Kim',
      passportNumber: 'JKL13579',
      phone: '555-4802',
      passengers: 2,
      price: '400.00',
      timestamp: '2023-08-01T12:00:00'
    },
    {
      id: '6',
      description: 'Multicity flight from Sydney to Melbourne to Brisbane',
      title: 'Sydney to Melbourne to Brisbane',
      productId: 'flight-006',
      mode: 'Flight',
      type: 'Multicity',
      from: 'Sydney',
      to: 'Brisbane',
      cities: ['Sydney', 'Melbourne', 'Brisbane'],
      status: 'Pending',
      reurntDepartureDateAndTime: '',
      returnArrivalDateAndTime: '',
      departureDateAndTime: '2023-11-01T06:00:00',
      arrivalDateAndTime: '2023-11-03T18:00:00',
      image: 'https://example.com/flight-image-6.jpg',
      email: 'emily@example.com',
      name: 'Emily Chen',
      passportNumber: 'MNO24680',
      phone: '555-5802',
      passengers: 3,
      price: '800.00',
      timestamp: '2023-08-01T12:00:00'
    },
    {
      id: '7',
      description: 'One way flight from Berlin to Munich',
      title: 'Berlin to Munich',
      productId: 'flight-007',
      mode: 'Flight',
      type: 'One Way',
      from: 'Berlin',
      to: 'Munich',
      cities: ['Berlin', 'Munich'],
      status: 'Approved',
      reurntDepartureDateAndTime: '',
      returnArrivalDateAndTime: '',
      departureDateAndTime: '2023-12-01T10:00:00',
      arrivalDateAndTime: '2023-12-01T12:00:00',
      image: 'https://example.com/flight-image-7.jpg',
      email: 'alex@example.com',
      name: 'Alex Müller',
      passportNumber: 'PQR46802',
      phone: '555-6914',
      passengers: 1,
      price: '150.00',
      timestamp: '2023-08-01T12:00:00'
    },
    {
      id: '8',
      description: 'Round trip flight from Toronto to Vancouver',
      title: 'Toronto to Vancouver Round Trip',
      productId: 'flight-008',
      mode: 'Flight',
      type: 'Round Trip',
      from: 'Toronto',
      to: 'Vancouver',
      cities: ['Toronto', 'Vancouver'],
      status: 'Cancelled',
      reurntDepartureDateAndTime: '2024-01-15T18:00:00',
      returnArrivalDateAndTime: '2024-01-22T21:00:00',
      departureDateAndTime: '2024-01-08T07:00:00',
      arrivalDateAndTime: '2024-01-08T10:00:00',
      image: 'https://example.com/flight-image-8.jpg',
      email: 'sophia@example.com',
      name: 'Sophia Nguyen',
      passportNumber: 'STU79135',
      phone: '555-7026',
      passengers: 2,
      price: '600.00',
      timestamp: '2023-08-01T12:00:00'
    },
    {
      id: '9',
      description: 'Multicity flight from Moscow to St. Petersburg to Kazan',
      title: 'Moscow to St. Petersburg to Kazan',
      productId: 'flight-009',
      mode: 'Flight',
      type: 'Multicity',
      from: 'Moscow',
      to: 'Kazan',
      cities: ['Moscow', 'St. Petersburg', 'Kazan'],
      status: 'Pending',
      reurntDepartureDateAndTime: '',
      returnArrivalDateAndTime: '',
      departureDateAndTime: '2024-02-10T08:00:00',
      arrivalDateAndTime: '2024-02-12T20:00:00',
      image: 'https://example.com/flight-image-9.jpg',
      email: 'ivan@example.com',
      name: 'Ivan Petrov',
      passportNumber: 'VWX02468',
      phone: '555-8138',
      passengers: 3,
      price: '900.00',
      timestamp: '2023-08-01T12:00:00'
    },
    {
      id: '10',
      description: 'One way flight from Rio de Janeiro to Sao Paulo',
      title: 'Rio de Janeiro to Sao Paulo',
      productId: 'flight-010',
      mode: 'Flight',
      type: 'One Way',
      from: 'Rio de Janeiro',
      to: 'Sao Paulo',
      cities: ['Rio de Janeiro', 'Sao Paulo'],
      status: 'Approved',
      reurntDepartureDateAndTime: '',
      returnArrivalDateAndTime: '',
      departureDateAndTime: '2024-03-01T14:00:00',
      arrivalDateAndTime: '2024-03-01T16:00:00',
      image: 'https://example.com/flight-image-10.jpg',
      email: 'maria@example.com',
      name: 'Maria Oliveira',
      passportNumber: 'YZA13579',
      phone: '555-9250',
      passengers: 1,
      price: '180.00',
      timestamp: '2023-08-01T12:00:00'
    }
  ];